services:
  - type: web
    name: chatooly-render-service
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MAX_CONCURRENT_JOBS
        value: 3
      - key: MAX_FRAMES_PER_JOB
        value: 300
      - key: MAX_RESOLUTION
        value: 4
      - key: CLEANUP_INTERVAL
        value: 3600000
      - key: CORS_ORIGIN
        value: https://yaelren.github.io